### ISSUE TITLE
January React meetup

### ISSUE THREAD

**Issue by maxlibin** [ReactJSSG/meetups#5] opened 2018-11-01 09:10 UTC
Title of your talk
**Intro to ReasonML**
**Intro to ReasonReact**

Tell us what you'd like to talk about
**Introduction to ReasonML**
**Introduction to ReasonReact**

Presenter(s)
**Introduction to ReasonML(by Bryan)**
**Introduction to ReasonReact(by Max)**

@yosriady

**Comment by yosriady** [comment] 2018-11-02 05:28
Hi @maxlibin, we won't be having any meetups for the rest of the year as I'm fully occupied with work and other commitments. 😃 

I'll register your interest to give a talk and let you know when we organize one in January. 👍

**Comment by maxlibin** [comment] 2018-11-02 06:11
Sure, unless someone else would like to co-organize? Especially now hook is such a big topic in react, maybe someone can share their experience in using it or tried it?

**Comment by thchia** [comment] 2018-11-03 10:17
I can do a talk on hooks, but I also think there’s no rush (they are technically still in alpha), so maybe January is better overall.

**Comment by yosriady** [comment] 2018-11-05 16:50
Let's do it in the first or second week ofJanuary since people are likely away in December.

**Comment by yosriady** [comment] 2018-11-15 03:16
## ℹ️ Details
- [x] [Meetup page](https://www.meetup.com/React-Singapore/events/256426835/)
- [x] Date: Thursday, 10th January 2019
- [x] Venue: TenX
- [x] Hosts: @yosriady

## 📅 Itinerary

Time   | Agenda
------ | :-----
7.00pm | Doors open - _mingle with guests and speakers over food and drinks_
7.20pm | Start of event - _opening segment by host_
7.30pm | Start of scheduled talks
8.40pm | Open announcements - _open segment for anyone to make announcements_
9.00pm | End of event

## 💬 Talks

> This could be you!

## 🎙 How to propose a talk

Want to give a talk? Leave a comment below with the following format:

> ## Title of your talk
>
> **Talk description**
>
> Tell us what you'd like to talk about
>
> **Presenter(s)**
>
> Include GitHub handles where possible. Add your Twitter handle if you wish
>
> **Presenter's bio**
>
> A short introduction of yourself
>
> **Duration requested**
>
> 10min, 20min, 30min
>
> **Slides URL (if any)**
>
> URL pointing to your slides (Google Slides, PDF, etc.) You can add this part in later.

## 📢 Open announcements

Have something you'd like to tell the audience? We have an open announcement segment for you to announce job opportunities, promote a meet up, upcoming conferences, etc. Please comment below to give the organizers a heads-up.

---

<details>
 <summary>📝 Organizers' checklist</summary>

- [x]  Confirm date and venue availability 
- [x]  Create event on [React JS SG Meetup Page](https://www.meetup.com/React-Singapore)

</details>

**Comment by yosriady** [comment] 2018-11-15 03:18
@maxlibin @thchia What do you guys think of Thursday, 10th January? Would you be interested to give a talk at this date?

**Comment by thchia** [comment] 2018-11-15 07:59
@yosriady tentatively OK but will have to re-confirm nearer the date...

**Comment by thchia** [comment] 2018-11-15 08:13
## Hooked on React
### Talk Description
An Introduction to the Hooks API in React.
* Why Hooks?
* Migrating to Hooks: State and 'Effects'
* Other Use Cases: Context and Reducers 👀 
* 🔥 **BONUS**: Testing Hooks 🔥 
### Presenter
Thomas Chia
:octocat: [github.com/thchia](github.com/thchia)
🐦 [@th__chia](twitter.com/th__chia)
### Presenter's Bio
Front End Developer, Lover of JavaScript, React, Serverless and other hype words.
### Duration Requested
30 mins (max)
### Slides URL
https://docs.google.com/presentation/d/1GldgG_y9XObBn7-y13Zi5YR_JmjxFjvFaGX-XQNuvjA/edit?usp=sharing

**Comment by yosriady** [comment] 2018-11-15 10:13
@maxlibin Let me know if the date is convenient for you, and please follow the format above for your talk proposals. 😄

**Comment by liaujianjie** [comment] 2018-11-15 16:03
## Client-side data architecture with Apollo Client

### Talk description (tentative scope)

* Brief GraphQL overview
* Why Apollo Client?
* Use cases & comparisons with common patterns
  * Caching responses from asynchronous API requests
  * Apollo links & some use cases
    * Auth routing guards
    * Retrying and deduping
* Using Apollo Client without a GraphQL endpoint (and incremental adoption)
* Other notable features
* Downsides & trade-offs

### Presenter(s)

Liau Jian Jie

:octocat: @liaujianjie
🐦 [@liaujianjie](https://twitter.com/liaujianjie)

### Presenter's bio

👨‍🎓 2nd year NUS CS undergrad passionate about product and performance.

### Duration requested

🕐 20min (max)

### Slides URL

🚧 I'm working on it!

**Comment by yosriady** [comment] 2018-11-20 08:43
Hi @liaujianjie, sounds good! Looking forward to see you at the event!

**Comment by yosriady** [comment] 2018-11-20 08:45
Hi @maxlibin Can you confirm your attendance at the event? I'd like to know if you'll be speaking in January.

**Comment by maxlibin** [comment] 2018-11-20 09:01
waiting for Bryan to add this content in, here is mine first.

### Intro to ReactReact
#### Talk description (tentative scope)
Brief ReasonReact overview
Why Reason React, why life will be easier with ReasonReact?
How to get started with reasonReact.
@maxlibin

Presenter's bio
👨‍🎓 Frontend dev @Ahrefs

Duration requested
🕐 20min - 30min (max)

**Comment by pulkitkkr** [comment] 2018-12-03 00:17
Hey,
I'm Pulkit, a React Evangelist and AR/VR enthusiast. It has been quite a while since I'm working with ReactJS and related Technologies. The world is shifting to another way of User Interfaces, AR & VR yet many React Developers are unaware how easy is it for them to adopt to the paradigm shift, I'm willing to contribute to the community and enlighten up the Audience about the same, would love to talk more about the same

Title:  Step into the future of UI: AR/VR with JavaScript

Current Position: Organizer, Facebook Developer Circle Delhi-NCR

Past Talks:    React Conf 2018, Las Vegas, USA
                       Video: https://www.youtube.com/watch?v=jd6FBBK1paA

Upcoming Talk:  ByteConf React-Native 2018,Scheduled for Dec 14th

Introduction to Talk: 

"React is a library to build intuitive User Interfaces" as quoted in official React documentation. The past few decades of computing have been limited to flat 2D screens. However, the rise of AR/VR means that society will soon move beyond the screen: where the UI won’t be a flat piece of glass but the 3D spaces in which we live & move around.

Since the inception of React, there have been multiple React-Renderer being made by community, One of them is ViroReact, a platform for Native AR/VR. The aim of Talk is to inspire attendees to create immersive, lag free cross-platform content using ViroReact. The talk tries to optimize the complex pathway to learn AR/VR into a linear one by laying the foundation of basic principles of AR/VR UIs and Illusions(Plausibility, Place & Embodiment).

Talk Flow:

A drastic change from 2D UIs to intuitive 3D UIs requires a detailed understanding of Three Illusions, Place Illusion, Plausibility Illusion, and Embodiment Illusion. Continuing after the introduction to the psychology of AR & VR, The misconception about AR/VR industry just being into entertainment will be ruled out from the hearts of the audience and pathway to inspiration will be laid toward the future, following which the 3-D geometry(Z-Axis) and understanding of basic transformations will be cleared out to the audience which is expected to know the basics of React & React-Native.

Once, the building blocks are established a gradual hands-on to AR/VR "Hello World" app will be made using live demonstration of Android ARCore based ViroReact App. The repository will be made public to the audience for future usage.

It will be followed by asking audience to keep clicking several photos during the talk and upload them to the Link shared just after the hello world app. Another code demo of 360 Images and Videos will be made using per-compiled APK of sample app, which also illustrate placement of 3D objects(.fbx) in the scene.

Finally a closing app will be showcased (not a demo) which will be dynamically made by the images uploaded by the live audience, and will leave the audience in awestruck  at the end, thereby inspiring the to learn more about the future of UIs AR & VR.

Unlike my previous talks, the talk will be more oriented toward scale-able AR VR code structuring with several code paradigms: 3D paradigm, Overlay Paradigm, Dynamical Route Overlay Paradigm etc.

About Me:

"UIs are not created but crafted, with imagination and core principles. The imaginations and core principles are fruit of Experience." 
Web Creation fascinated me since I was 14 years of age, Ever since then I follow the strategy of "Run, Walk or Crawl: But Keep moving".
Choosing a niche segment had always been my cup of tea, be it choosing BlackBerry 10 Platform to develop app for when everyone were opting for Android and iOS and and ending up being selected among Top 250 Developers, with Apps being listed in top Apps in BlackBerry App Store.

Another Example of choosing a totally unexpected segment of mine is selecting Feature Phone segment to develop Mobile Apps for, and ending up being getting selected as Nokia Asha Premium Member by developing 12+ Apps for Nokia Asha 501 feature phone Platform at that's all at the age of 17.

Following the drastic fall of both of my mainstream platforms, Nokia & BlackBerry, I opted to learn AngularJS 1.x, ionic Framework and Phonegap and deployed Mobile Apps for Major organizations like Rotaract Club of MSIT and PowerGrid India (Government Agency) at the age of 18, But again the community saw major leap from AngularJs 1.x to 2.x.

So finally, I got introduced to ever new intuitive world of ReactJS, which I'm following since the release of version 13.x, Using the ReactJs, have Developed for Raspberry pi (using React-Hardware), Have Developed production level mobile Apps using React-Native for various freelance clients. And have provided client support and training to people working at major Tech Giants like Walmart, Well Fargo, Microsoft etc.
Coming to the world of VR/AR to which I just got introduced by the Mr. Satyajeet Singh, Head - Strategic Product Partnerships, India & South Asia last year while giving a talk on React at Facebook Developer Circle Delhi at the age of 20. I started learning native VR content development using Unity 3d, but ended up exploring more & more about learnt philosophy and skills implementation using ReactJS, and finally got introduced to ViroReact Platform.
Closing with my initial quote "UIs are not created but crafted, with imagination and core principles. The imaginations and core principles are fruit of Experience."

I assure to deliver the best of my experiences to introduce the Frontend and React Community to future of UI.

-- 
Regards
Pulkit Kakkar 
Organizing Team
Facebook Developer Circle: Delhi-NCR
Ph: +91-9711187234
Mail: pulkitkkr@gmail.com

**Comment by yosriady** [comment] 2018-12-03 04:01
Hi @pulkitkkr, we're all full for the January meetup - would you be available to present on a future meetup? (tentatively mid-February or early March)

**Comment by pulkitkkr** [comment] 2018-12-03 08:23
@yosriady I'm ok with early Feb dates (1st to 12th) also will be needing travel and accommodation allowance

**Comment by yosriady** [comment] 2018-12-04 06:10
@pulkitkkr We don't give travel and accommodation allowance. Speaking slots are on a strictly free (as in beer) basis.

**Comment by yosriady** [comment] 2019-01-02 02:36
@maxlibin @thchia @liaujianjie 

Happy new year!
Looking forward to see you next Thursday (10th January) and to listen to what you have to share. 😃 
Please comment so I can confirm your attendance for the meetup.

**Comment by maxlibin** [comment] 2019-01-02 04:34
@yosriady 👍

**Comment by liaujianjie** [comment] 2019-01-02 10:16
@yosriady I'll be there, happy new year everyone! 😄

**Comment by thchia** [comment] 2019-01-05 01:01
👌

**Comment by yosriady** [comment] 2019-01-10 02:57
@maxlibin @thchia @liaujianjie 

Hi folks! Looking forward to seeing you at our first React meetup of 2019. Due to overwhelming response, the event location has moved to a larger venue:

Huone Events Hotel Singapore
3D River Valley Road #03-01, 
Singapore 179023(above Hai Di Lao Clarke Quay)

---

**How to get there**

[Directions Map](https://drive.google.com/open?id=1MaRuYHPBg0bDLQWAuYcIhZrTt4bNN082&usp=sharing)

From the Clarke Quay MRT, walk out towards the river, cross the Read Bridge, and walk along the other side of the river to locate the Huone Events Hotel.

**Comment by liaujianjie** [comment] 2019-01-10 10:55
Hey @yosriady I'm gonna run a bit late, will be there around 7:30-ish

**Comment by yosriady** [comment] 2019-01-10 11:03
@yosriady Sure no problem, come and find me later to set up your laptop.

**Comment by yosriady** [comment] 2019-01-10 11:25
![20190110_182729](https://user-images.githubusercontent.com/1084226/50965583-55d08d80-150d-11e9-9b0b-5f2c48dd6cd3.jpg)

@liaujianjie Come and find me to set up your laptop. You can also follow the instructions above once you're in the room. (But don't start presenting yet.) I'll be sitting closest to the speaker.

**Comment by yosriady** [comment] 2019-01-10 14:15
@maxlibin @thchia @liaujianjie 

Great talks everybody!  🎉 🥇  💯 
Feel free to share links to your slides by commenting on [the Meetup page](https://www.meetup.com/React-Singapore/events/256426835/).
Thank you for sharing!

**Closed as completed by yosriady** 2019-01-10 14:15 UTC
